import { z } from "zod";

// Shapes of the website JSON contract, as captured in fixtures/golden/ (see
// fixtures/golden/README.md). Each schema doubles as the drift detector: it
// validates both the frozen golden fixture files (lib/publish/schemas.test.ts)
// and this generator's own output (lib/publish/artifacts/*.test.ts) — the
// same contract, checked from both directions.
//
// awards.json and upcoming-games.json are deliberately not covered here —
// KAN-30 doesn't generate them (see docs/02-architecture.md's publish
// pipeline section for why).

const PlayerSeasonStatsArtifactSchema = z.object({
  season: z.string(),
  games: z.number().int(),
  goals: z.number().int(),
  assists: z.number().int(),
  pims: z.number().int(),
  points: z.number().int(),
  warriorOfTheGame: z.number().int().optional(),
  manOfTheMatch: z.number().int().optional(),
});

const PlayerArtifactSchema = z.object({
  id: z.string(),
  name: z.string(),
  nickname: z.string().optional(),
  number: z.number().int(),
  position: z.string(),
  stats: z.array(PlayerSeasonStatsArtifactSchema),
});

export const PlayersArtifactSchema = z.array(PlayerArtifactSchema);

export const RosterConfigArtifactSchema = z.object({
  activePlayers: z.array(z.string()),
});

const TeamSeasonStatsArtifactSchema = z.object({
  season: z.string(),
  games: z.number().int(),
  goalsFor: z.number().int(),
  pims: z.number().int(),
  goalsAgainst: z.number().int(),
  wins: z.number().int(),
  draws: z.number().int(),
  losses: z.number().int(),
});

export const TeamArtifactSchema = z.object({
  stats: z.array(TeamSeasonStatsArtifactSchema),
});

const ResultGoalArtifactSchema = z.object({
  playerId: z.string(),
  // The legacy fixture pads unused assist slots with literal `null` entries
  // (always on opponentGoals, which never tracked assists at all) rather
  // than omitting them — accepted here so the fixture itself validates; our
  // generator never emits null, only a shorter array.
  assists: z.array(z.string().nullable()),
  minute: z.number().int(),
  second: z.number().int(),
  type: z.string(),
});

const ResultPenaltyArtifactSchema = z.object({
  offender: z.string(),
  minute: z.number().int(),
  second: z.number().int(),
  type: z.string(),
  duration: z.number(),
});

const ResultPeriodArtifactSchema = z.object({
  warriorsScore: z.number().int(),
  opponentScore: z.number().int(),
  goals: z.array(ResultGoalArtifactSchema),
  opponentGoals: z.array(ResultGoalArtifactSchema),
  penalties: z.array(ResultPenaltyArtifactSchema),
  opponentPenalties: z.array(ResultPenaltyArtifactSchema),
});

const ResultArtifactSchema = z.object({
  season: z.string(),
  opponentTeam: z.string(),
  // Not generated by KAN-30 — no opponent-logo data source exists yet
  // (deferred alongside awards.json/upcoming-games.json). Present on every
  // entry in the golden fixture, so kept optional here rather than dropped,
  // to keep this one schema valid against both the fixture and our output.
  logoImage: z.string().optional(),
  date: z.string(),
  seasonId: z.string(),
  roster: z.array(z.string()),
  // "MISSING" is the legacy sentinel for a genuinely unset award/netminder —
  // preserved deliberately, see lib/publish/artifacts/results.ts.
  manOfTheMatchPlayerId: z.string(),
  warriorOfTheGamePlayerId: z.string(),
  netminderPlayerId: z.string(),
  competition: z.string(),
  location: z.string(),
  score: z.object({
    warriorsScore: z.number().int(),
    opponentScore: z.number().int(),
    period: z.object({
      one: ResultPeriodArtifactSchema,
      two: ResultPeriodArtifactSchema,
      three: ResultPeriodArtifactSchema,
    }),
  }),
});

export const ResultsArtifactSchema = z.array(ResultArtifactSchema);
